In [23]:
#task 1(1)
def func1(a,b):
    c=0
    try:
        c=a/b
        print(c)
    except ZeroDivisionError:
        print("Second value cannot be zero")
    except:
        print("try after some time")
    finally:
        print("thank you")
d=int(input("enter first number"))
e=int(input("enter second number"))
func1(d,e)
d=int(input("enter first number"))
e=int(input("enter second number"))
func1(d,e)
 

enter first number4
enter second number6
0.6666666666666666
thank you
enter first number4
enter second number0
Second value cannot be zero
thank you


In [24]:
#task 1(2)
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for a in subjects:
    for b in verbs:
        for c in objects:
            print(a+" "+b+" "+c)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [1]:
#Task 2(1)
def VanderMonde(a,b):
    c=a.split(",")
    d=[]
    for i in c:  
        d.append(int(i))
    f=[]
    for i in d:
        e=[]
        for j in range(b-1,-1,-1):
            e.append(i**j)
        f.append(e)
    import numpy as np
    g=np.array(f)
    return g
a=input("enter the comma seperated number sequence")
b=int(input("enter number of columns in output matrix"))
print(VanderMonde(a,b))
a=input("enter the comma seperated number sequence")
b=int(input("enter number of columns in output matrix"))
VanderMonde(a,b)
        

enter the comma seperated number sequence1,2,3,4
enter number of columns in output matrix3
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]
enter the comma seperated number sequence1,2,3,4
enter number of columns in output matrix4


array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])